apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql
    name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "B4teau123!"
      - name: MYSQL_PASSWORD
        value: "root"
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: mysql-configmap
            key: database
      - name: MYSQL_USER
        valueFrom: 
          configMapKeyRef:
            name: mysql-configmap
            key: database
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
